Numpy Learning

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [3]:
a = [1,2,3,'hello']
a

[1, 2, 3, 'hello']

In [4]:
np.array(a)

array(['1', '2', '3', 'hello'], dtype='<U21')

In [5]:
l = [[1,2,3], [4,5,6] , [7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array Generation function

In [7]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [9]:
arr = np.zeros(4)
arr

array([0., 0., 0., 0.])

In [10]:
arr = np.zeros((4, 4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
arr = np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [12]:
arr = np.ones((6, 6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [13]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

linspace having same space between them and syntax is (start, end, how many number)

In [14]:
arr = np.linspace(1,5,2)
arr

array([1., 5.])

In [15]:
arr = np.linspace(1,5,10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

Random Generation function

In [16]:
np.random.rand(5)

array([0.81935124, 0.98847878, 0.75060519, 0.30853176, 0.69120365])

In [17]:
np.random.randn(5)

array([1.0696534 , 0.4623265 , 0.85431162, 0.31083372, 0.15868644])

In [21]:
np.random.randint(10,20,10)

array([17, 16, 12, 12, 19, 12, 10, 15, 17, 15], dtype=int32)

Array Attributes

In [24]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
arr.shape

(3, 3)

In [26]:
arr.size

9

In [27]:
arr.dtype

dtype('int64')

Array Methods