Numpy Learning

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [3]:
a = [1,2,3.5,'hello']
a

[1, 2, 3.5, 'hello']

In [4]:
np.array(a)

array(['1', '2', '3.5', 'hello'], dtype='<U32')

In [5]:
l = [[1,2,3], [4,5,6] , [7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array Generation function

In [7]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [9]:
arr = np.zeros(4)
arr

array([0., 0., 0., 0.])

In [10]:
arr = np.zeros((4, 4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
arr = np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [12]:
arr = np.ones((6, 6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [13]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

linspace having same space between them and syntax is (start, end, how many number)

In [14]:
arr = np.linspace(1,5,2)
arr

array([1., 5.])

In [15]:
arr = np.linspace(1,5,10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

Random Generation function

In [16]:
np.random.rand(5)

array([0.67640477, 0.57390614, 0.02532243, 0.98636015, 0.82437751])

In [17]:
np.random.randn(5)

array([-1.25588313, -1.14215678, -0.10907487, -0.37623784,  2.62392293])

In [18]:
np.random.randint(10,20,10)

array([14, 16, 19, 11, 16, 17, 17, 12, 16, 16], dtype=int32)

Array Attributes

In [19]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
arr.shape

(3, 3)

In [21]:
arr.size

9

In [22]:
arr.dtype

dtype('int64')

Array Methods

In [23]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
arr.min()

np.int64(1)

In [25]:
arr.max()

np.int64(9)

In [26]:
arr.sum()

np.int64(45)

Reshaping & Resizing

In [27]:
arr = np.arange(1, 31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [28]:
arr.reshape(6, 5)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

Resizing: Reshape ko arr me save kar lo ab jab bhi "arr" ko call karoge toh reshape wala hi aayega

In [32]:
arr = arr.reshape(6, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])