In [1]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [6]:
a = [1,2,3,'hello']
a

[1, 2, 3, 'hello']

In [7]:
np.array(a)

array(['1', '2', '3', 'hello'], dtype='<U21')

In [8]:
l = [[1,2,3], [4,5,6] , [7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [17]:
arr = np.zeros(4)
arr

array([0., 0., 0., 0.])

In [18]:
arr = np.zeros((4, 4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])